name: update-tag

on:
  pull_request:
    types: closed
jobs:
  pull-request-merged:
    name: On pull request merged
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        && contains(github.head_ref, 'releases') || contains(github.head_ref, 'hotfix') 
    steps:  
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Extract tag
        shell: bash
        run: echo "##[set-output name=new-tag;]$(declare -a list=$(git tag); python scripts/generate-tag.py ${list[*]})"
        id: extract_tag

    
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout master
          git tag -a ${{steps.extract_tag.outputs.new-tag}} HEAD -m "added tag"
          git push --tags

